decoration {

  rounding = 10

  blur {
    enabled = true
    size = 5
    passes = 3
    ignore_opacity = true
    popups = true
    new_optimizations = true
  }

  shadow {
    enabled = true
    range = 4
  }
}
