input {
	kb_layout = de
        kb_variant = 
	kb_model = 
	kb_options = 
	kb_rules =
	
	follow_mouse = 1
	accel_profile = flat
	sensitivity = 0

	touchpad {
	    natural_scroll = true
	    scroll_factor = 0.3
	}
}

device {
	name = razer-orochi-v2
	sensitivity = -0.5
	accel_profile = flat
	}
device {
	name = razer-orochi-v2-1
	sensitivity = -0.5
	accel_profile = flat
	}
device {
	name = razer-orochi-v2-2
	sensitivity = -0.5
	accel_profile = flat
	}
device {
	name = razer-orochi-v2-3
	sensitivity = -0.5
	accel_profile = flat
	}
device {
	name = razer-orochi-v2-4
	sensitivity = -0.5
	accel_profile = flat
	}
device {
	name = razer-orochi-v2-5
	sensitivity = -0.5
	accel_profile = flat
	}
device {
	name = PixArt HP 125 USB Optical Mouse
	sensitivity = -0.5
	accel_profile = flat
	}
